title: Vehiculos Autonomos QCAR
description: Documentaci√≥n del proyecto QCAR usando Just the Docs

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://sebas30073007.github.io"
baseurl: "/Vehiculos_autonomos_QCAR"

aux_links:
  GitHub Repository: https://github.com/sebas30073007/Vehiculos_autonomos_QCAR
